// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InlineEditController from "./inline_edit_controller"

application.register("inline-edit", InlineEditController)

import ToggleCompletionController from "./toggle_completion_controller"
application.register("toggle-completion", ToggleCompletionController)

import FormValidationController from "./form_validation_controller"

application.register("form-validation", FormValidationController)